### ISSUE TITLE
Is this working also in YT, if yes, it's not working...

### ISSUE THREAD

**Issue by edcarSky** [singhsidhukuldeep/request-boost#1]
not working on me... can you pls help

C:\Python36\request-boost-main>setup.py
Traceback (most recent call last):
  File "C:\Python36\request-boost-main\setup.py", line 11, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools

**Comment by singhsidhukuldeep** [comment]
Do
pip install setuptools

**Comment by edcarSky** [comment]
youtube

**Comment by edcarSky** [comment]
C:\Python36\request-boost-main>pip install setuptools
Requirement already satisfied: setuptools in c:\python36\lib\site-packages (28.8.0)

C:\Python36\request-boost-main>setup.py
Traceback (most recent call last):
  File "C:\Python36\request-boost-main\setup.py", line 11, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools

**Comment by singhsidhukuldeep** [comment]
this is a generic tool,

it wraps internal default python libraries in multiprocessing.

This is a generic library and can be used for any GET/POST request!
