### ISSUE TITLE
Update on pypi

### ISSUE THREAD

**Issue by tferreira** [singhsidhukuldeep/request-boost#11]
Hi singhsidhukuldeep,

Thanks a lot for the library, it has been really helpful for a [tool](https://github.com/tferreira/topbid) I've created!
I am encountering a `KeyError` when reaching the timeout on some requests, and I see it has been fixed by this commit: https://github.com/singhsidhukuldeep/request-boost/commit/d78edf4bd740558d8f2585f8bfbd52d4e1e21313

However the library hasn't been updated on pypi.org since more than a year.
I think it would be really convenient to have a new version containing this patch. Would you be able to build/upload one if you have some time please?

Have a nice day!

**Comment by singhsidhukuldeep** [comment]
DONE

https://pypi.org/project/request-boost/0.7/
