### ISSUE TITLE
Can boosted requests inherit a session's authentication?

### ISSUE THREAD

**Issue by sgoley** [singhsidhukuldeep/request-boost#5]
Was somewhat inspired by this SO question but I'm wondering if it's possible for the boosted requests to inherit any properties from something like a requests session? Specifically the authentication piece which is very helpful.

https://stackoverflow.com/questions/44020439/session-auth-in-python

``` python
with requests.sessions.Session() as session:
    session.auth = ("username", "password")
    
    # Make any requests here without provide auth info again
    session.get("http://www.example.com/users")
```

My use case is an authenticated api that doesn't have a bulk endpoint 🤦‍♂️🤦‍♂️
Consequently, I have to send something like the following request on loop:
`session.get("http://www.example.com/users/<userid>")`

Right now, my only option is attempting to "impersonate" my Postman / Insomnia authorization by copying the hashed Authorization directly into a static key on the header. 

Something like: 
`headers = [{'API_KEY': 'my_key', 'Authorization': 'Basic asdfjl1234567890='} for user_id in range(len(all_user_ids))]`

**Comment by singhsidhukuldeep** [comment]
Hey mate

Few things,
Currently I/we are using urllib to make the API calls, i don't know if there is an authentication method like requests

I have this planned as a [ToDo](https://github.com/singhsidhukuldeep/request-boost#todo-want-to-contribute) to have multiple backends so have requests also as an option (will make sure we are able to port the authentication system as well) 

I think you can just keep your authentication data as ENV variables and pass them to boosted_requests as you have suggested above. 

If you have more ideas that might improve this please contribute 🙂

**Comment by sgoley** [comment]
From what I'm reading in the docs [urllib -> BasicAuth](https://docs.python.org/3.1/howto/urllib2.html#id6), `password_mgr` & `opener` seem to be used in a somewhat similar manner but yeah - ENV works just as well for my current use case. 
Just thinking of later on if I ever run into a similar use case that forces Oauth or something less static header friendly.
